# This workflow sets up an R environment on GitHub Actions,
# installs dependencies, and runs checks on your R package.
# The workflow uses third-party actions provided by r-lib and other contributors.

name: R

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.1']  # Specify the R version to use in the workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out your repository code

      - name: Set up R
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}  # Sets up the specified R version

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))  # Installs required packages
          remotes::install_deps(dependencies = TRUE)   # Installs package dependencies
        shell: Rscript {0}

      - name: Run package checks
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")  # Runs R CMD check
        shell: Rscript {0}
